# Creando una sistema de Algebra Lineal

In [1]:
import numpy as np    # Importo librería NumPy como np

### Creo clase con métodos para realizar operaciones de álgebra lineal con vectores y matrices

In [2]:
class Array:
    #----------[ Metodo constructor y validador:
    def __init__(self, list_of_rows): 
        "Constructor y validador"
        # obtener dimensiones
        self.data = list_of_rows
        nrow = len(list_of_rows)
        
        #  ___caso vector: redimensionar correctamente
        if not isinstance(list_of_rows[0], list):
            nrow = 1
            self.data = [[x] for x in list_of_rows]
        
        # ahora las columnas deben estar bien aunque sea un vector
        ncol = len(self.data[0])
        self.shape = (nrow, ncol)
        
        # validar tamano correcto de filas
        if any([len(r) != ncol for r in self.data]):
            raise Exception("Las filas deben ser del mismo tamano")
    #---------- Metodo constructor y validador ].
    
    
    #----------[ Metodo para imprimir sin función Print:
    def __repr__(self):
        rows = self.shape[0]
        data_out = "array(["
        for i in range(rows):
            if i == (rows - 1):
                data_out += "       " + str(self.data[i]) + "])"
            elif i != 0:
                data_out += "       " + str(self.data[i]) + "," + "\n"
            else:
                data_out += str(self.data[i]) + "," + "\n"
            
        return (data_out)
    #---------- Metodo para imprimir sin función Print ].


    #----------[ Metodo para imprimir con función Print: 
    def __str__(self):
        rows = self.shape[0]
        data_out = "["
        for i in range(rows):
            if i == (rows - 1):
                data_out += " " + str(self.data[i]) + "]"
            elif i != 0:
                data_out += " " + str(self.data[i]) + "\n"
            else:
                data_out += str(self.data[i]) + "\n"
            
        return (data_out)
    #---------- Metodo para imprimir con función Print ].
    
    
    #----------[ Metodo para obtener un item: 
    def __getitem__(self, idx, ini=0):
        if ini == 0:
            return self.data[idx[0]][idx[1]]
        else:
            return self.data[(idx[0] - 1)][(idx[1] -1) ]
    #---------- Metodo para obtener un item ].
    
    
    #----------[ Metodo para modificar un item:
    def __setitem__(self, idx, new_value, ini=0):
        if ini == 0:
            self.data[idx[0]][idx[1]] = new_value
        else:
            self.data[(idx[0] - 1)][(idx[1] -1)] = new_value
        
        return new_value
    #---------- Metodo para modificar un item ].
    

    #----------[ Metodo para generar la matriz transpuesta:
    def transpose(self):
        nrow, ncol = self.shape
        newArray = Array([[0. for c in range(ncol)] for r in range(nrow)])
        for i in range(nrow):            
            for j in range(ncol):
                newArray.data[j][i] = self.data[i][j]

        return(newArray)
    #---------- Metodo para generar la matriz transpuesta ].
    
    
    #----------[ Metodo para sumar arrays:
    def __add__(self, other):
        if isinstance(other, Array):
            if self.shape != other.shape:
                raise Exception("Las dimensiones son distintas!")
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] + other.data[r][c]
            return newArray
        elif isinstance(2, (int, float, complex)): # en caso de que el lado derecho sea solo un numero
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] + other
            return newArray
        else:
            return NotImplemented # es un tipo de error particular usado en estos metodos
    #---------- Metodo para sumar arrays ].

    
    #----------[ Metodo para restar arrays:
    def __sub__(self, other):
        if isinstance(other, Array):
            if self.shape != other.shape:
                raise Exception("Las dimensiones son distintas!")
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] - other.data[r][c]
            return newArray
        elif isinstance(2, (int, float, complex)): # en caso de que el lado derecho sea solo un numero
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] - other
            return newArray
        else:
            return NotImplemented # es un tipo de error particular usado en estos metodos
    #---------- Metodo para restar arrays ].
    
    
    #----------[ Metodo para sumar arrays:
    def __mul__(self, other):
        pass
    #---------- Metodo para sumar arrays ].

    
#----------[ Función para crear Matriz de Ceros:
def zeros(shape):
    list_of_rows = []
    for i in range(shape[0]):
        list_of_rows.append([0 for x in range(shape[1])]) 
              
    return(list_of_rows)
#---------- Función para crear Matriz de Ceros ].


#----------[ Función para crear Matriz Identidad:
def eye(n,k=0):
    list_of_rows = []
    for i in range(n):
        list_of_zeros = [0 for x in range(n)]
        # Calculo indice para generar matriz identiad:
        idx = (i + k)   
        if (idx >= 0) & (idx <= (n - 1)):
            # Asigno 1 a la pos. determinada
            list_of_zeros[idx] = 1      
        
        list_of_rows.append(list_of_zeros)     
              
    return(list_of_rows)
#---------- Función para crear Matriz Identidad ].

In [3]:
A = Array([[1,2,3], [4,5,6],[7,8,9]])
A.__dict__     # el campo escondido __dict__ permite acceder a las propiedades de clase de un objeto

{'data': [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 'shape': (3, 3)}

In [4]:
A.data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
A.shape

(3, 3)

In [6]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(A)

[[1, 2, 3]
 [4, 5, 6]
 [7, 8, 9]]


In [8]:
A.__getitem__([1,1])

5

In [9]:
A.__setitem__([2,2],5,1)

5

In [10]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
z = zeros((2,2))
z

[[0, 0], [0, 0]]

In [12]:
c = Array(zeros((2,2)))

In [13]:
c

array([[0, 0],
       [0, 0]])

In [14]:
d = Array(eye(4,k=0))
d

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [15]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
T = A.transpose()
T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [17]:
sum = A + T
sum

array([[2, 6, 10],
       [6, 10, 14],
       [10, 14, 18]])

In [18]:
mult = A * T
mult